### ISSUE TITLE
The blog is private

### ISSUE THREAD

**Issue by matclab** [yinwang0/pysonar2#55]
Accessing https://yinwang0.wordpress.com/2010/09/12/pysonar gives : 

```
https://yinwang0.wordpress.com/ is marked private by its owner. If you were invited to view this site, please log in below. Read more about privacy settings.
```

**Comment by sindhus** [comment]
I get a 404 now.

**Comment by songjinghe** [comment]
Yin has make up his mind to be a man who would give us more wisdom/tips to make PROGRAMMER's life more easy and pleased----from a cultural view----because he found it's not the tools we use that provide us the happiness, but the respect and some other things. In one word, there are more things we should value other than computer tools. 

Most of his tech article is not public nor under maintainence. some maybe deleted. You should look for a web cache site which may store the orginal article. His [chinese blog](http://www.yinwang.org) is under active updates, however, its main idea is nolonger about tools, nor has tech details as before.
