### ISSUE TITLE
Why pysonar doesn't handle InstanceType's attribute modification

### ISSUE THREAD

**Issue by bryce-ma** [yinwang0/pysonar2#82]
![pysonar1](https://cloud.githubusercontent.com/assets/16175037/21560446/552d8fec-ce9a-11e6-817a-75736bf22604.png)

I just wonder why pysonar doesn't behave like python interpreter. The example above shows that the type of variable `c` is inferred to be `str` type, but python interpreter will evaluate it as `int`  type.

I can not find the author's email address, so I put this question in here and any explanations will be appreciated.

**Comment by yinwang0** [comment]
Modifying the type of a field like this is impractical to track down, so pysonar will only take the first type. Even if it handles your case, you can make it even more complex to defeat it. In general this is good enough because modifying the type of a field in confusing and will not be frequently used.

**Comment by bryce-ma** [comment]
Thanks for explaining this.
